### ISSUE TITLE
[Minor]Search Bar is not editable 

### ISSUE THREAD

**Issue by amoghdave** [Boneato/bonito#11]
Description: 
in the view where the search is showing relevant ingredients from the search bar, the search is not editable 

Steps to recreate: 
1) search for an ingredient ie "Ketchup"
2) the website displays all the ketchups in a list 
3) If I change my mind and want to search for "Mustard" instead, I can't do that without clicking on find ingredients again

expected behavior: 
the ingredient that is searched for and is in quotations up top should be editable and I should be able to type in "mustard" after deleting "ketchup"

OS: MacOS
Browser: Safari
<img width="1680" alt="Screen Shot 2019-12-05 at 5 02 06 PM" src="https://user-images.githubusercontent.com/3924743/70286679-fa406b80-1780-11ea-8994-cc91e6d420aa.png">

**Comment by anthonyqcn** [comment]
For record keeping purposes, marking as duplicate of [issue 12](https://github.com/Boneato/bonito/issues/12)
