### ISSUE TITLE
[minor] Search Bar Is Not Editable

### ISSUE THREAD

**Issue by amoghdave** [Boneato/bonito#12]
Description:
in the view where the search is showing relevant ingredients from the search bar, the search is not editable

Steps to recreate:

search for an ingredient ie "Ketchup"
the website displays all the ketchups in a list
If I change my mind and want to search for "Mustard" instead, I can't do that without clicking on find ingredients again
expected behavior:
the ingredient that is searched for and is in quotations up top should be editable and I should be able to type in "mustard" after deleting "ketchup"

OS: MacOS
Browser: Safari
<img width="1680" alt="Screen Shot 2019-12-05 at 5 10 16 PM" src="https://user-images.githubusercontent.com/3924743/70286962-1db7e600-1782-11ea-9704-7cf122bc1464.png">

**Comment by Uyedacb** [comment]
This feature was never intended in our launch and is considered an enhancement. This won't be worked on.
