### ISSUE TITLE
[MAJOR] Going back after finding clicking on a result

### ISSUE THREAD

**Issue by ccforbes** [Boneato/bonito#13]
**Describe the bug**
Not correctly going back to the correct page

**To Reproduce**
1. Clicked on "About Us"
2. Clicked on "Find Ingredient"
3. Queried "bonito"
4. Clicked on first link result
5. Clicked back on browser
6. Goes to "About Us"

**Expected behavior**
From the result page of the specific ingredient, the expectation was to go back to the list view of all the results.

**Screenshots**

**Additional context**

**Comment by anthonyqcn** [comment]
clicking back now takes you to the previous results list page as of a8a61343f35555cff97a7f9151f987ea8a803fae
