### ISSUE TITLE
[minor] cannot go back from search result page to homepage

### ISSUE THREAD

**Issue by alexh5** [Boneato/bonito#14]
After searching a food and being redirected to the homepage, the user cannot go back to the homepage.

**To Reproduce**
1. Load the homepage
2. Type something in the search bar
3. Press Enter
4. Attempt to go back

**Expected behavior**
After pressing back from the result page, the user should be redirected to the homepage.

**Screenshots**
![hello](https://user-images.githubusercontent.com/32464069/70287221-06c5c380-1783-11ea-962f-2a96e4222bd5.PNG)
As seen here, the back button is grayed out or not clickable after a search.

**Comment by anthonyqcn** [comment]
Able to click back now, and it takes you to the previous results list page as of commit a8a61343f35555cff97a7f9151f987ea8a803fae
