### ISSUE TITLE
[minor] About us profiles are clickable but provide no functionality

### ISSUE THREAD

**Issue by alexh5** [Boneato/bonito#15]
**Describe the bug**
When clicking the profile cards for each team member in the about page, there is no added functionality.

**To Reproduce**
1. Go to the About Page
2. Click on a profile card

**Expected behavior**
There should be some functionality or added information on the individual after clicking on them. If there shouldn't be any added functionality, the profile card should not be clickable.

**Comment by Uyedacb** [comment]
working on

**Comment by Uyedacb** [comment]
Issue has been fixed, thanks for the feedback
