### ISSUE TITLE
[minor] Not redirected after sign in

### ISSUE THREAD

**Issue by tfpenner** [Boneato/bonito#17]
**Describe the bug**
The user stays on the login page when they sign in

**To Reproduce**
1. Click on the login tab in the upper right.
2. Sign in with Google

**Expected behavior**
I expected to be redirected to the home page, but there isn't any obvious feedback on whether I was successfully logged in

**Screenshots**
This is shown immediately after I sign in
<img width="1252" alt="Screen Shot 2019-12-05 at 5 41 16 PM" src="https://user-images.githubusercontent.com/53621324/70288414-7a1d0480-1786-11ea-857f-dec468dd43b5.png">

**Additional context**
Using Google Chrome on a MacBook Pro

**Comment by Uyedacb** [comment]
redirect now works
