### ISSUE TITLE
[minor] Cannot unclick confirm/didn't find

### ISSUE THREAD

**Issue by Aimee0103wu** [Boneato/bonito#18]
**Describe the bug**
Once clicked on one of the buttons(confirm and didn't find), It cannot be unclicked.

**To Reproduce**
1. Go to site
2. Search for a product
3. click on either confirm or didn't find
4. See error: cannot unclick or click on the other option

**Expected behavior**
I expect the options can be undone since there is possibility of clicking on the button by mistakes. I also think it should allow the users to be able to choose both of the options since the users might be able to find the product once but later on, cannot find it at the same store.

**Screenshots**

**Additional context**

**Comment by Uyedacb** [comment]
Won't be able to fix this before the deadline. Currently putting all my time into fixing a current bug where page won't load after redirect from sign in menu. Putting higher priority on fixing that bug.

As a note, to fix this bug will have to check firestore data to see if user has voted and create conditional buttons.
