### ISSUE TITLE
[minor] Multiple Search & Clicking Back doesn't update results

### ISSUE THREAD

**Issue by CD6-timury** [Boneato/bonito#19]
**Describe the bug**
If you search for an ingridient, then you go to search for a next ingridient, but you remember that you forgot some item & you click back (i.e. in your browser) - the url up top changes, so does the text in the display up top with # of results, however the results themselves don't change.

**To Reproduce**
1. Go to 'Find Ingredients'
2. Search for any item (in my case - i searched for 'Pepper')
3. Click on 'Find Ingredients'
4. Search for another item (in my case - I searched for 'Onion')
5. Go back to previous page
6. See error

**Expected behavior**
First of all, it should actually redirect to homepage. But even if it does redirect to the previous search query - it should display the results of that search query.

**Screenshots**
https://cdn.discordapp.com/attachments/621827871832276992/652375651650633738/unknown.png

**Additional context**
OS: Windows 10 Enterprise (1803)
Browser (Version 78.0.3904.108 64 Bit)

**Comment by anthonyqcn** [comment]
Can you find another way to share the screnshot? the image isn't loading for me.

**Comment by CD6-timury** [comment]
![image](https://user-images.githubusercontent.com/8738747/70364661-5a4b1680-1842-11ea-92f8-16a9da510317.png)

**Comment by anthonyqcn** [comment]
Doing multiple searches resets the search to display results for most recent search now as of commit a8a61343f35555cff97a7f9151f987ea8a803fae
