### ISSUE TITLE
[minor] The page doesn't refresh after enter a new location.

### ISSUE THREAD

**Issue by tran6388-1672747** [Boneato/bonito#20]
**Describe the bug**
After I have entered a new location for a certain ingredient like "chili cheese", there are no feedback or the page get re-render to show the user that the location have successful upload. I have to click the refresh button to see the new update. I think this is bug that you need to fix, because as a user, i expect to see the change right after i click submit or ok.

**To Reproduce**
1. Go to 'https://bonito-collab.firebaseapp.com/SpecIngPage/xqk4Xwx659a9v86N8lur'
2. Click on 'Report a new location'
3. Enter a new location like "Hoover Dam, Nevada, USA"
4. See error: the page does not re-render to see the change.

**Expected behavior**
Expect the see the added city right the way after click submit.

**Screenshots**
![Screenshot (71)](https://user-images.githubusercontent.com/23422230/70365111-9f704800-1844-11ea-9e52-f14729b29db2.png)

**Additional context**

**Comment by anthonyqcn** [comment]
Reporting a new location now updates to display the new location with a map pin as of commit e92205fd55b8622bc987ad43ec0df011dac668b0
