### ISSUE TITLE
[minor] Login feature not moving back to the search page.

### ISSUE THREAD

**Issue by tran6388-1672747** [Boneato/bonito#21]
**Describe the bug**
This is not a bug, so you don't have to worry about it. But, I just want to point out something. While I was searching for an ingredient like "chili". I got to the place of the ingredient. If I want to add new place, I have to sign in. I see that you have a sign in button that will move me to the sign in page. But after sign in with Google. The page does not transfer me back to the chili page, but I have to do the extra step and go to the find ingredient and start the search again. This is not user friendly. User have very limit attention span, so they can give easily if you leave it like this.

**To Reproduce**
1. Go to 'https://bonito-collab.firebaseapp.com/'
2. Enter a search like "chili"
3. Scroll down and pick: "corn chips, chili cheese"
4. Click "Sign in with google"
5. Move to the sign in page and sign in.
4. See error: does not move back to the chili page.

**Expected behavior**
As a user, I really like move back to search place like chili page. I don't want to spend the extra step to go back because it is very tired and slow.

**Screenshots**

![Screenshot (72)](https://user-images.githubusercontent.com/23422230/70365535-b4e67180-1846-11ea-989c-057a8603fc89.png)

![Screenshot (73)](https://user-images.githubusercontent.com/23422230/70365541-bca61600-1846-11ea-84de-e3cba395cd96.png)

**Additional context**

**Comment by Uyedacb** [comment]
redirect works now
