### ISSUE TITLE
[MAJOR] 404 Site down?

### ISSUE THREAD

**Issue by Kyrabautista** [Boneato/bonito#23]
**Describe the bug**
This may just be unlucky timing, but
https://boneato.github.io/ is down. It refuses to load components and all I see is a 404 error page.

**To Reproduce**
1. Go to https://boneato.github.io/
2. See 404 "There isn't a Github pages site here"

**Expected behavior**
Expected the site to show

**Screenshots**
![error2](https://user-images.githubusercontent.com/32441997/70383279-f565ee00-191f-11ea-8938-12f5e69bdf28.PNG)
![error3](https://user-images.githubusercontent.com/32441997/70383280-f565ee00-191f-11ea-84be-22e87f9a6910.PNG)
![error1](https://user-images.githubusercontent.com/32441997/70383281-f5fe8480-191f-11ea-9a5a-eeac8256bf43.PNG)

**Additional context**
OS: Windows 10
Browser: Chrome
Ver 78.0.3904.108

**Comment by anthonyqcn** [comment]
Our website is at https://bonito-collab.firebaseapp.com/ not bonito.github.io.
