### ISSUE TITLE
[minor]Result page still shows "loading" even if there is no results found

### ISSUE THREAD

**Issue by GarsonYang** [Boneato/bonito#25]
**Describe the bug**
The search result page still shows "loading" even if there is no results found.

**To Reproduce**
1. Go to the home page.
2. Input anything that doesn't result in any search result (like "egggy")
3. Click on the search button
4. See the "loading" notice forever.

**Expected behavior and rationale**
There shouldn't be the "loading" notice because it may be misleading.

**Comment by anthonyqcn** [comment]
Duplicate of [issue 16](https://github.com/Boneato/bonito/issues/16)
