### ISSUE TITLE
[minor]Potential misleading page update mechanism

### ISSUE THREAD

**Issue by GarsonYang** [Boneato/bonito#26]
**Describe the bug**
When the user enters a ingredient page with location info, the page will first load "Phooey. There are no known locations yet." and then update it with the info. That is inaccurate and would be misleading if the user has a slow network connection

**To Reproduce**
1. Go to the home page
2. Input "tomato" and click on the search button.
3. Click on the "tomatoes, vine ripened".
4. See the notice

**Expected behavior**
Consider not to update the "not found" notice with the actual info but shows "loading" or something like that.

**Comment by Uyedacb** [comment]
currently working on

**Comment by Uyedacb** [comment]
Thanks for the feedback. Currently debating whether or not to add a loading screen as this may effect the flow of the application. However, the "phooey no locations" should not display if an ingredient has a location. Will re-open if I add a loading screen.
