### ISSUE TITLE
[MAJOR] Functionality issue

### ISSUE THREAD

**Issue by 3ickey** [Boneato/bonito#28]
**Describe the bug**
After I report a new location, that location is not associated with the ingredient at all and the app still says "Phooey. There are no known locations yet."

**To Reproduce**

1. Log in
2. Go to 'Search' and search for any ingredient
3. From the list select the one that matches the ingredient
4. Click on 'Report a new location'
5. Enter the location and click on 'Submit'
6. See error where the page still says "Phooey. There are no known locations yet." although you just added one.

**Expected behavior**
I expect the entered location to be associated with the searched ingredient and also show up on the map.

**Desktop**
 - OS: macOS
 - Browser: Safari

**Comment by Uyedacb** [comment]
Can you submit a screenshot? I just tested it and it seems to work for me.

**Comment by Uyedacb** [comment]
Closing until more information is given.
