### ISSUE TITLE
[major] Any ingredient search always gives error " Phooey. There are no known locations yet."

### ISSUE THREAD

**Issue by poojaram** [Boneato/bonito#29]
**Describe the bug**
First I'm unable to sign in with my google account and it redirects to a null page. Searching any food item produces a result - Phooey. There are no known locations yet.

**To Reproduce**
1. Go to Find Ingredients
2. Search anything (eg. 'Carrot Cake')
3. See that there are no suggested locations to buy

**Expected behavior**
The expected behaviour was to display a list of locations where I can possibly find the ingredient searched for, but none was displayed and this is the result for all searches.

**Screenshots**
![Screen Shot 2019-12-09 at 2 26 43 PM](https://user-images.githubusercontent.com/28207016/70478509-0897cb80-1a90-11ea-9685-3f40aa4db63b.png)

**Comment by Uyedacb** [comment]
Carrot cake has no locations submitted for it so this is the correct display for carrot cake. Also please submit reproducible steps/screenshots that show the google sign-in is not working.

**Comment by Uyedacb** [comment]
Closing until more information is given
