### ISSUE TITLE
[MAJOR] Signing in with google

### ISSUE THREAD

**Issue by anuraagpolisetty** [Boneato/bonito#5]
**Describe the bug**
I looked up 'Bonito' and clicked on "Bonito, in Olive Oil" and from the resulting page I clicked on 
"Please sign in with Google" and it resulted in an endless refresh of the page or it redirected to a 404 page.

**To reproduce**
1. Looked up 'Bonito'
2. Clicked on "Bonito, in Olive OIl"
3. Click on "Please sign in with google at the top"

**Expected**
A sign in page with google

**Comment by anthonyqcn** [comment]
Sign in with google has now become possible since 3 days ago with commit 0a8096cd21aa01b3374393517974e40dd7a3fe50
