### ISSUE TITLE
[Minor] No favicon and web title

### ISSUE THREAD

**Issue by albertli354** [Boneato/bonito#7]
**Bug description**
The favicon and the website title are still the default react image and "React App". It does not hurt the functionality, but I think it supposed to reflect the website's content.  

**To reproduce**
1. Open the homepage. 

**Expected behavior**
The favicon and website title should reflect the website content. 
![image](https://user-images.githubusercontent.com/26781751/70286358-c0bb3080-177f-11ea-8be7-d3bc1f63c55a.png)

**Comment by xCyziw** [comment]
Added favicon and website title.
