### ISSUE TITLE
[minor] No alert when search-bar is empty

### ISSUE THREAD

**Issue by albertli354** [Boneato/bonito#9]
**Bug Description**
When I entered nothing in the search bar and hit the search button, the website still directs me to the result page showing the result of null. I think it is better to give users an alert before searching for an empty string. 

**To reproduce**
1. Go to the homepage.
2. Hit the search bar.
3. The search result shows the result of an empty string. 

**Expected behavior**
An alert telling users they are searching for an empty string. 
![image](https://user-images.githubusercontent.com/26781751/70285476-7dab8e00-177c-11ea-93f4-1f39ff512a86.png)

**Comment by Uyedacb** [comment]
currently working on

**Comment by Uyedacb** [comment]
Search bar will now output an error if it is empty, preventing any empty searches.
